repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # UV lock file check
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.7
    hooks:
      - id: uv-lock
        name: Check uv.lock is up to date
        args: [--locked]

  # Semantic commit message validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

